profiles {
    standard {
        process.executor = 'local'
    }

    cantb {
        process.executor = 'slurm'
        process.queue = 'tb'
        process.memory = '256GB'
        process.cpus = 20
        process.conda = '<%= condaEnv %>'
    }
    canfs {
        process.executor = 'slurm'
        process.queue = 'fast'
        process.memory = '64GB'
        process.cpus = 4
        process.conda = '<%= condaEnv %>'
    }

}
conda.enabled = true

process.maxErrors = 10
process.maxRetries = 20